[project]
name = "Stagehand"
dependencies = [
  "ahk==0.14.2",
  "ahk-binary==1.1.33.9",
  "appdirs",
  "click",
  "codex-engine-pyqt",
  "cyberlang",
  "inquirerpy",
  "monaco-qt",
  "numpy",
  "pygame-ce",
  "psutil",
  "pydantic==1.10.8",
  "pynput",
  "pyserial",
  "PySide6==6.5.2",
  "QtAwesome",
  "QtPy",
  "qtstrap",
  "sounddevice",
  "superqt",
]