[project]
name = "Stagehand"
description = "An event-based desktop automation tool for Windows, Linux, and macOS."
readme = "README.md"
license = { text = "MIT License" }
version = "2024.0.0"
authors = [{ name = "David Kincaid", email = "dlkincaid0@gmail.com" }]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

requires-python = ">= 3.10"
dependencies = [
    "ahk==0.14.2",
    "ahk-binary==1.1.33.9",
    "appdirs",
    "click",
    "codex-engine-pyqt",
    "cyberlang",
    "inquirerpy",
    "monaco-qt",
    "numpy",
    "pygame-ce",
    "psutil",
    "pydantic==1.10.8",
    "pynput",
    "pyserial",
    "PySide6==6.7.0",
    "QtAwesome",
    "QtPy",
    "qtstrap",
    "sounddevice",
    "superqt",
]

[project.gui-scripts]
spam-gui = "app:main"
